### ISSUE TITLE
Add individual processor methods and grammar compilers

### ISSUE THREAD

**Issue by kevindierkx** [kevindierkx/elicit#5]
Currently all request are processed using the ```$processor->processRequest($builder, $request)``` call. This works fine in most use cases but it would be better to abstract this to individual methods.
Same goes for the grammar, everything is compiled the same way. Once again this isn't a huge problem but it would be better to abstract this to specific methods for the request calls used.

**Comment by nielstholenaar** [comment]
I'll have a look.

**Comment by kevindierkx** [comment]
Merged your changes related to the individual processor methods.

**Comment by kevindierkx** [comment]
Can't remember why I would want to split the grammar class.. Closing this for now.
